### ISSUE TITLE
Fix = Row 0  Parquet file is loaded

### ISSUE THREAD

**Issue by SoftTools59654** [l1xnan/duckling#30]
Only at the time of the first loading of the Parquet file

This is not a problem, but when the Parquet file is loaded, the line is 0. Therefore, the sample file cannot be loaded. It is much better to set it to 100 by default.

The custom Row button doesn't work either

![asdfsd](https://github.com/l1xnan/DuckStudio/assets/150426297/963a1d6e-cfe3-47f4-a0a3-b08692423e90)

**Comment by l1xnan** [comment]
Is this still a problem with the latest version?

**Comment by SoftTools59654** [comment]
In the test I did, I did not see any problem in the latest version. Probably the problem is solved

I will report again if there is a problem
