### ISSUE TITLE
The possibility of editing the folder and the problem of loading the folder

### ISSUE THREAD

**Issue by SoftTools59654** [l1xnan/duckling#33]
The possibility of editing the folder and the problem of loading the folder

It is not possible to add a database to the old folder

When there are several databases in a folder and a file unrelated to the database, if we select that folder, the entire program will be closed. Although there are several databases inside that folder

**Comment by tim-tepia** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @yhchiang-sol, @brooksprumo, @sjquant, @vitorribeiro99, @reloot-v-reboot, @vitali2y, @qiuzhuangshandian, @lolipopshock, @OxPatient, @H0301ein, @richizo, @OmoleAdesoji, @gregorybfoulkes, @ivanerre, @gwho, @itsHall, @dalechn, @Fav4858, @gzliudan, @yigitatakan, @sleepysnowman, @bodytexture, @cancelei, @Akramz, @guweigang, @mgautam98, @helxsz, @chrish42, @umegbewe, @Rhyanz46, @lippytm, @fatihcandev, @mohammedaugie13, @liratanak, @mikostel, @SOLmoon2025, @Shib4, @Alex-Beh, @derangedarcheologist, @evertonfraga0, @ameya-deshmukh, @dzyls, @ouyun, @derkdewit, @itzPromorpheusxviii, @danielgospodinow, @kodjunkie, @ikapeykin, @chengchangwu, @guanhuaw

**Comment by tim-tepia** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @rhizome01, @sarmatdev, @gabrielfernandeslima, @javaddehban, @chrisckwong821, @YiHan-HuaHua, @eaorak, @hoganri, @funnymania, @rauschy33, @chenjunwen186, @GDdark, @minwiki7456, @kewarrie, @Karimhouilia, @bhuwanadhikari, @MatteoGauthier, @biobox18, @hifizz, @0nkery, @He1pa, @shasa, @ctyl3r, @yocalemooos, @rafaelfess, @LenilsonTomaz, @christophersk, @lomashuk, @ErnestK, @sujal, @izayacity, @wegamekinglc, @showlovel, @jebu, @j16r, @nfa1, @martinraag, @Digitalurchman, @ApricotComputers, @PedroHLC, @G-R-8, @JustStakeIT, @Gopi-Durgaprasad, @croccifixio-maneki, @2020-io, @gsspdev, @kafaichoi, @romance08, @peterkinalex, @BestNathan

**Comment by l1xnan** [comment]
Sorry for the missed appointment. The problem of program closure may be due to the abnormal exit of the program caused by the failure to get the file extension (I have encountered), now it has been fixed. Currently, the folder can only read parquet/csv and other static data files, other files will be filtered out, duckdb database files need to be added separately. The duckdb database file needs to be added separately. I would like to know what is your usage scenario?

**Comment by SoftTools59654** [comment]
When there are a number of files with different types of extensions in a folder
For example, csv and Parquet are loaded without problems
But if there is a sample text file among those files, none of the files will be loaded

The problem can be solved. Just by choosing these two extensions
